substitutions:
  board: esp32-c3-devkitm-1
  name: 'garage-lights'
  name_add_mac_suffix: true
  north_off_pin: GPIO9
  north_on_pin: GPIO10
  platform: esp-idf
  press_duration: 500ms
  project_name: 'dudemcbacon.${name}'
  project_version: '1.0'
  south_off_pin: GPIO7
  south_on_pin: GPIO8
  yamlfile: garage-lights.yaml

packages:
  base: !include common/base.yaml

# Define GPIO outputs
output:
  - platform: gpio
    pin: ${south_on_pin}
    id: output_south_on
  - platform: gpio
    pin: ${south_off_pin}
    id: output_south_off
  - platform: gpio
    pin: ${north_on_pin}
    id: output_north_on
  - platform: gpio
    pin: ${north_off_pin}
    id: output_north_off

# Define buttons that trigger the outputs for 500ms
button:
  - platform: output
    name: 'Garage South Light On'
    output: output_south_on
    duration: ${press_duration}
    icon: 'mdi:lightbulb-on'

  - platform: output
    name: 'Garage South Light Off'
    output: output_south_off
    duration: ${press_duration}
    icon: 'mdi:lightbulb-off'

  - platform: output
    name: 'Garage North Light On'
    output: output_north_on
    duration: ${press_duration}
    icon: 'mdi:lightbulb-on'

  - platform: output
    name: 'Garage North Light Off'
    output: output_north_off
    duration: ${press_duration}
    icon: 'mdi:lightbulb-off'
